spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:

server:
  port:

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
